///////////////////////////////////////////////////////////
//  LoginUserInfo.as
//  用户收藏的服务数据结构类
//  Generated by Enterprise Architect
//  Created on:      09-04-2012 16:51:03
//  Original author: 温杨彪
///////////////////////////////////////////////////////////
package com.esri.viewer
{
	
	[RemoteClass(alias="com.esrichina.portal.flex.pojo.LoginUser")]
	[Bindable]
	/**
	 * 登录用户信息
	 * @author 温杨彪；2012-4-9
	 **/
	public class LoginUser
	{
		public var userId:int;
		/**
		 * 用户名，用户登录名，为唯一的
		 **/
		public var userName:String;
		/**
		 * 用户别名，用户显示名
		 **/
		public var fullName:String;
		
		/**
		 * 用户密码。出于安全考虑，为空字符串
		 **/
		public var password:String;
		public var token:String;
		//访问服务的Token
		public var agsToken:String;
		
		public var ifPortalManager:String;
		
		public var tel:String;
		
		public var email:String;
		
		public function LoginUser()
		{
		}
	}
}